export const timezones = {
  table: "timezones",
  rows: [
    {
      id: 1,
      name: "Africa/Abidjan",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 2,
      name: "Africa/Accra",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 3,
      name: "Africa/Addis_Ababa",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 4,
      name: "Africa/Algiers",
      gmt_offset_january: 1,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 5,
      name: "Africa/Asmera",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 6,
      name: "Africa/Bamako",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 7,
      name: "Africa/Bangui",
      gmt_offset_january: 1,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 8,
      name: "Africa/Banjul",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 9,
      name: "Africa/Bissau",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 10,
      name: "Africa/Blantyre",
      gmt_offset_january: 2,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 11,
      name: "Africa/Brazzaville",
      gmt_offset_january: 1,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 12,
      name: "Africa/Bujumbura",
      gmt_offset_january: 2,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 13,
      name: "Africa/Cairo",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 14,
      name: "Africa/Casablanca",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 15,
      name: "Africa/Ceuta",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 16,
      name: "Africa/Conakry",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 17,
      name: "Africa/Dakar",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 18,
      name: "Africa/Dar_es_Salaam",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 19,
      name: "Africa/Djibouti",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 20,
      name: "Africa/Douala",
      gmt_offset_january: 1,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 21,
      name: "Africa/El_Aaiun",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 22,
      name: "Africa/Freetown",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 23,
      name: "Africa/Gaborone",
      gmt_offset_january: 2,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 24,
      name: "Africa/Harare",
      gmt_offset_january: 2,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 25,
      name: "Africa/Johannesburg",
      gmt_offset_january: 2,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 26,
      name: "Africa/Kampala",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 27,
      name: "Africa/Khartoum",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 28,
      name: "Africa/Kigali",
      gmt_offset_january: 2,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 29,
      name: "Africa/Kinshasa",
      gmt_offset_january: 1,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 30,
      name: "Africa/Lagos",
      gmt_offset_january: 1,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 31,
      name: "Africa/Libreville",
      gmt_offset_january: 1,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 32,
      name: "Africa/Lome",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 33,
      name: "Africa/Luanda",
      gmt_offset_january: 1,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 34,
      name: "Africa/Lubumbashi",
      gmt_offset_january: 2,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 35,
      name: "Africa/Lusaka",
      gmt_offset_january: 2,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 36,
      name: "Africa/Malabo",
      gmt_offset_january: 1,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 37,
      name: "Africa/Maputo",
      gmt_offset_january: 2,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 38,
      name: "Africa/Maseru",
      gmt_offset_january: 2,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 39,
      name: "Africa/Mbabane",
      gmt_offset_january: 2,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 40,
      name: "Africa/Mogadishu",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 41,
      name: "Africa/Monrovia",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 42,
      name: "Africa/Nairobi",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 43,
      name: "Africa/Ndjamena",
      gmt_offset_january: 1,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 44,
      name: "Africa/Niamey",
      gmt_offset_january: 1,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 45,
      name: "Africa/Nouakchott",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 46,
      name: "Africa/Ouagadougou",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 47,
      name: "Africa/Porto-Novo",
      gmt_offset_january: 1,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 48,
      name: "Africa/Sao_Tome",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 49,
      name: "Africa/Tripoli",
      gmt_offset_january: 2,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 50,
      name: "Africa/Tunis",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 51,
      name: "Africa/Windhoek",
      gmt_offset_january: 2,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 52,
      name: "America/Adak",
      gmt_offset_january: -10,
      dst_offset_july: -9,
      type: "original",
    },
    {
      id: 53,
      name: "America/Anchorage",
      gmt_offset_january: -9,
      dst_offset_july: -8,
      type: "original",
    },
    {
      id: 54,
      name: "America/Anguilla",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 55,
      name: "America/Antigua",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 56,
      name: "America/Araguaina",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 57,
      name: "America/Argentina/Buenos_Aires",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 58,
      name: "America/Argentina/Catamarca",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 59,
      name: "America/Argentina/Cordoba",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 60,
      name: "America/Argentina/Jujuy",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 61,
      name: "America/Argentina/La_Rioja",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 62,
      name: "America/Argentina/Mendoza",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 63,
      name: "America/Argentina/Rio_Gallegos",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 64,
      name: "America/Argentina/San_Juan",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 65,
      name: "America/Argentina/Tucuman",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 66,
      name: "America/Argentina/Ushuaia",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 67,
      name: "America/Aruba",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 68,
      name: "America/Asuncion",
      gmt_offset_january: -3,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 69,
      name: "America/Bahia",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 70,
      name: "America/Barbados",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 71,
      name: "America/Belem",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 72,
      name: "America/Belize",
      gmt_offset_january: -6,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 73,
      name: "America/Boa_Vista",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 74,
      name: "America/Bogota",
      gmt_offset_january: -5,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 75,
      name: "America/Boise",
      gmt_offset_january: -7,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 76,
      name: "America/Cambridge_Bay",
      gmt_offset_january: -7,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 77,
      name: "America/Campo_Grande",
      gmt_offset_january: -3,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 78,
      name: "America/Cancun",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 79,
      name: "America/Caracas",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 80,
      name: "America/Cayenne",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 81,
      name: "America/Cayman",
      gmt_offset_january: -5,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 82,
      name: "America/Chicago",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 83,
      name: "America/Chihuahua",
      gmt_offset_january: -7,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 84,
      name: "America/Coral_Harbour",
      gmt_offset_january: -5,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 85,
      name: "America/Costa_Rica",
      gmt_offset_january: -6,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 86,
      name: "America/Cuiaba",
      gmt_offset_january: -3,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 87,
      name: "America/Curacao",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 88,
      name: "America/Danmarkshavn",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 89,
      name: "America/Dawson",
      gmt_offset_january: -8,
      dst_offset_july: -7,
      type: "original",
    },
    {
      id: 90,
      name: "America/Dawson_Creek",
      gmt_offset_january: -7,
      dst_offset_july: -7,
      type: "original",
    },
    {
      id: 91,
      name: "America/Denver",
      gmt_offset_january: -7,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 92,
      name: "America/Detroit",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 93,
      name: "America/Dominica",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 94,
      name: "America/Edmonton",
      gmt_offset_january: -7,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 95,
      name: "America/Eirunepe",
      gmt_offset_january: -5,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 96,
      name: "America/El_Salvador",
      gmt_offset_january: -6,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 97,
      name: "America/Fortaleza",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 98,
      name: "America/Glace_Bay",
      gmt_offset_january: -4,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 99,
      name: "America/Godthab",
      gmt_offset_january: -3,
      dst_offset_july: -2,
      type: "original",
    },
    {
      id: 100,
      name: "America/Goose_Bay",
      gmt_offset_january: -4,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 101,
      name: "America/Grand_Turk",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 102,
      name: "America/Grenada",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 103,
      name: "America/Guadeloupe",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 104,
      name: "America/Guatemala",
      gmt_offset_january: -6,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 105,
      name: "America/Guayaquil",
      gmt_offset_january: -5,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 106,
      name: "America/Guyana",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 107,
      name: "America/Halifax",
      gmt_offset_january: -4,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 108,
      name: "America/Havana",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 109,
      name: "America/Hermosillo",
      gmt_offset_january: -7,
      dst_offset_july: -7,
      type: "original",
    },
    {
      id: 110,
      name: "America/Indiana/Indianapolis",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 111,
      name: "America/Indiana/Knox",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 112,
      name: "America/Indiana/Marengo",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 113,
      name: "America/Indiana/Petersburg",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 114,
      name: "America/Indiana/Vevay",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 115,
      name: "America/Indiana/Vincennes",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 116,
      name: "America/Inuvik",
      gmt_offset_january: -7,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 117,
      name: "America/Iqaluit",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 118,
      name: "America/Jamaica",
      gmt_offset_january: -5,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 119,
      name: "America/Juneau",
      gmt_offset_january: -9,
      dst_offset_july: -8,
      type: "original",
    },
    {
      id: 120,
      name: "America/Kentucky/Louisville",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 121,
      name: "America/Kentucky/Monticello",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 122,
      name: "America/La_Paz",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 123,
      name: "America/Lima",
      gmt_offset_january: -5,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 124,
      name: "America/Los_Angeles",
      gmt_offset_january: -8,
      dst_offset_july: -7,
      type: "original",
    },
    {
      id: 125,
      name: "America/Maceio",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 126,
      name: "America/Managua",
      gmt_offset_january: -6,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 127,
      name: "America/Manaus",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 128,
      name: "America/Martinique",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 129,
      name: "America/Mazatlan",
      gmt_offset_january: -7,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 130,
      name: "America/Menominee",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 131,
      name: "America/Merida",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 132,
      name: "America/Mexico_City",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 133,
      name: "America/Miquelon",
      gmt_offset_january: -3,
      dst_offset_july: -2,
      type: "original",
    },
    {
      id: 134,
      name: "America/Moncton",
      gmt_offset_january: -4,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 135,
      name: "America/Monterrey",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 136,
      name: "America/Montevideo",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 137,
      name: "America/Montreal",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 138,
      name: "America/Montserrat",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 139,
      name: "America/Nassau",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 140,
      name: "America/New_York",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 141,
      name: "America/Nipigon",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 142,
      name: "America/Nome",
      gmt_offset_january: -9,
      dst_offset_july: -8,
      type: "original",
    },
    {
      id: 143,
      name: "America/Noronha",
      gmt_offset_january: -2,
      dst_offset_july: -2,
      type: "original",
    },
    {
      id: 144,
      name: "America/North_Dakota/Center",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 145,
      name: "America/North_Dakota/New_Salem",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 146,
      name: "America/Panama",
      gmt_offset_january: -5,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 147,
      name: "America/Pangnirtung",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 148,
      name: "America/Paramaribo",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 149,
      name: "America/Phoenix",
      gmt_offset_january: -7,
      dst_offset_july: -7,
      type: "original",
    },
    {
      id: 150,
      name: "America/Port_of_Spain",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 151,
      name: "America/Port-au-Prince",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 152,
      name: "America/Porto_Velho",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 153,
      name: "America/Puerto_Rico",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 154,
      name: "America/Rainy_River",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 155,
      name: "America/Rankin_Inlet",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 156,
      name: "America/Recife",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 157,
      name: "America/Regina",
      gmt_offset_january: -6,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 158,
      name: "America/Rio_Branco",
      gmt_offset_january: -5,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 159,
      name: "America/Santiago",
      gmt_offset_january: -3,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 160,
      name: "America/Santo_Domingo",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 161,
      name: "America/Sao_Paulo",
      gmt_offset_january: -2,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 162,
      name: "America/Scoresbysund",
      gmt_offset_january: -1,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 163,
      name: "America/Shiprock",
      gmt_offset_january: -7,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 164,
      name: "America/St_Johns",
      gmt_offset_january: -3,
      dst_offset_july: -2,
      type: "original",
    },
    {
      id: 165,
      name: "America/St_Kitts",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 166,
      name: "America/St_Lucia",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 167,
      name: "America/St_Thomas",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 168,
      name: "America/St_Vincent",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 169,
      name: "America/Swift_Current",
      gmt_offset_january: -6,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 170,
      name: "America/Tegucigalpa",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 171,
      name: "America/Thule",
      gmt_offset_january: -4,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 172,
      name: "America/Thunder_Bay",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 173,
      name: "America/Tijuana",
      gmt_offset_january: -8,
      dst_offset_july: -7,
      type: "original",
    },
    {
      id: 174,
      name: "America/Toronto",
      gmt_offset_january: -5,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 175,
      name: "America/Tortola",
      gmt_offset_january: -4,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 176,
      name: "America/Vancouver",
      gmt_offset_january: -8,
      dst_offset_july: -7,
      type: "original",
    },
    {
      id: 177,
      name: "America/Whitehorse",
      gmt_offset_january: -8,
      dst_offset_july: -7,
      type: "original",
    },
    {
      id: 178,
      name: "America/Winnipeg",
      gmt_offset_january: -6,
      dst_offset_july: -5,
      type: "original",
    },
    {
      id: 179,
      name: "America/Yakutat",
      gmt_offset_january: -9,
      dst_offset_july: -8,
      type: "original",
    },
    {
      id: 180,
      name: "America/Yellowknife",
      gmt_offset_january: -7,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 181,
      name: "Antarctica/Casey",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 182,
      name: "Antarctica/Davis",
      gmt_offset_january: 7,
      dst_offset_july: 7,
      type: "original",
    },
    {
      id: 183,
      name: "Antarctica/DumontDUrville",
      gmt_offset_january: 10,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 184,
      name: "Antarctica/Mawson",
      gmt_offset_january: 6,
      dst_offset_july: 6,
      type: "original",
    },
    {
      id: 185,
      name: "Antarctica/McMurdo",
      gmt_offset_january: 13,
      dst_offset_july: 12,
      type: "original",
    },
    {
      id: 186,
      name: "Antarctica/Palmer",
      gmt_offset_january: -3,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 187,
      name: "Antarctica/Rothera",
      gmt_offset_january: -3,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 188,
      name: "Antarctica/South_Pole",
      gmt_offset_january: 13,
      dst_offset_july: 12,
      type: "original",
    },
    {
      id: 189,
      name: "Antarctica/Syowa",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 190,
      name: "Antarctica/Vostok",
      gmt_offset_january: 6,
      dst_offset_july: 6,
      type: "original",
    },
    {
      id: 191,
      name: "Arctic/Longyearbyen",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 192,
      name: "Asia/Aden",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 193,
      name: "Asia/Almaty",
      gmt_offset_january: 6,
      dst_offset_july: 6,
      type: "original",
    },
    {
      id: 194,
      name: "Asia/Amman",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 195,
      name: "Asia/Anadyr",
      gmt_offset_january: 12,
      dst_offset_july: 13,
      type: "original",
    },
    {
      id: 196,
      name: "Asia/Aqtau",
      gmt_offset_january: 5,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 197,
      name: "Asia/Aqtobe",
      gmt_offset_january: 5,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 198,
      name: "Asia/Ashgabat",
      gmt_offset_january: 5,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 199,
      name: "Asia/Baghdad",
      gmt_offset_january: 3,
      dst_offset_july: 4,
      type: "original",
    },
    {
      id: 200,
      name: "Asia/Bahrain",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 201,
      name: "Asia/Baku",
      gmt_offset_january: 4,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 202,
      name: "Asia/Bangkok",
      gmt_offset_january: 7,
      dst_offset_july: 7,
      type: "original",
    },
    {
      id: 203,
      name: "Asia/Beirut",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 204,
      name: "Asia/Bishkek",
      gmt_offset_january: 6,
      dst_offset_july: 6,
      type: "original",
    },
    {
      id: 205,
      name: "Asia/Brunei",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 206,
      name: "Asia/Calcutta",
      gmt_offset_january: 5,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 207,
      name: "Asia/Choibalsan",
      gmt_offset_january: 9,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 208,
      name: "Asia/Chongqing",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 209,
      name: "Asia/Colombo",
      gmt_offset_january: 5,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 210,
      name: "Asia/Damascus",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 211,
      name: "Asia/Dhaka",
      gmt_offset_january: 6,
      dst_offset_july: 6,
      type: "original",
    },
    {
      id: 212,
      name: "Asia/Dili",
      gmt_offset_january: 9,
      dst_offset_july: 9,
      type: "original",
    },
    {
      id: 213,
      name: "Asia/Dubai",
      gmt_offset_january: 4,
      dst_offset_july: 4,
      type: "original",
    },
    {
      id: 214,
      name: "Asia/Dushanbe",
      gmt_offset_january: 5,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 215,
      name: "Asia/Gaza",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 216,
      name: "Asia/Harbin",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 217,
      name: "Asia/Hong_Kong",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 218,
      name: "Asia/Hovd",
      gmt_offset_january: 7,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 219,
      name: "Asia/Irkutsk",
      gmt_offset_january: 8,
      dst_offset_july: 9,
      type: "original",
    },
    {
      id: 220,
      name: "Asia/Jakarta",
      gmt_offset_january: 7,
      dst_offset_july: 7,
      type: "original",
    },
    {
      id: 221,
      name: "Asia/Jayapura",
      gmt_offset_january: 9,
      dst_offset_july: 9,
      type: "original",
    },
    {
      id: 222,
      name: "Asia/Jerusalem",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 223,
      name: "Asia/Kabul",
      gmt_offset_january: 4,
      dst_offset_july: 4,
      type: "original",
    },
    {
      id: 224,
      name: "Asia/Kamchatka",
      gmt_offset_january: 12,
      dst_offset_july: 13,
      type: "original",
    },
    {
      id: 225,
      name: "Asia/Karachi",
      gmt_offset_january: 5,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 226,
      name: "Asia/Kashgar",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 227,
      name: "Asia/Katmandu",
      gmt_offset_january: 5,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 228,
      name: "Asia/Krasnoyarsk",
      gmt_offset_january: 7,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 229,
      name: "Asia/Kuala_Lumpur",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 230,
      name: "Asia/Kuching",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 231,
      name: "Asia/Kuwait",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 232,
      name: "Asia/Macau",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 233,
      name: "Asia/Magadan",
      gmt_offset_january: 11,
      dst_offset_july: 12,
      type: "original",
    },
    {
      id: 234,
      name: "Asia/Makassar",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 235,
      name: "Asia/Manila",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 236,
      name: "Asia/Muscat",
      gmt_offset_january: 4,
      dst_offset_july: 4,
      type: "original",
    },
    {
      id: 237,
      name: "Europe/Nicosia",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "modified",
    },
    {
      id: 238,
      name: "Asia/Novosibirsk",
      gmt_offset_january: 6,
      dst_offset_july: 7,
      type: "original",
    },
    {
      id: 239,
      name: "Asia/Omsk",
      gmt_offset_january: 6,
      dst_offset_july: 7,
      type: "original",
    },
    {
      id: 240,
      name: "Asia/Oral",
      gmt_offset_january: 5,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 241,
      name: "Asia/Phnom_Penh",
      gmt_offset_january: 7,
      dst_offset_july: 7,
      type: "original",
    },
    {
      id: 242,
      name: "Asia/Pontianak",
      gmt_offset_january: 7,
      dst_offset_july: 7,
      type: "original",
    },
    {
      id: 243,
      name: "Asia/Pyongyang",
      gmt_offset_january: 9,
      dst_offset_july: 9,
      type: "original",
    },
    {
      id: 244,
      name: "Asia/Qatar",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 245,
      name: "Asia/Qyzylorda",
      gmt_offset_january: 6,
      dst_offset_july: 6,
      type: "original",
    },
    {
      id: 246,
      name: "Asia/Rangoon",
      gmt_offset_january: 6,
      dst_offset_july: 6,
      type: "original",
    },
    {
      id: 247,
      name: "Asia/Riyadh",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 248,
      name: "Asia/Saigon",
      gmt_offset_january: 7,
      dst_offset_july: 7,
      type: "original",
    },
    {
      id: 249,
      name: "Asia/Sakhalin",
      gmt_offset_january: 10,
      dst_offset_july: 11,
      type: "original",
    },
    {
      id: 250,
      name: "Asia/Samarkand",
      gmt_offset_january: 5,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 251,
      name: "Asia/Seoul",
      gmt_offset_january: 9,
      dst_offset_july: 9,
      type: "original",
    },
    {
      id: 252,
      name: "Asia/Shanghai",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 253,
      name: "Asia/Singapore",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 254,
      name: "Asia/Taipei",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 255,
      name: "Asia/Tashkent",
      gmt_offset_january: 5,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 256,
      name: "Asia/Tbilisi",
      gmt_offset_january: 4,
      dst_offset_july: 4,
      type: "original",
    },
    {
      id: 257,
      name: "Asia/Tehran",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 258,
      name: "Asia/Thimphu",
      gmt_offset_january: 6,
      dst_offset_july: 6,
      type: "original",
    },
    {
      id: 259,
      name: "Asia/Tokyo",
      gmt_offset_january: 9,
      dst_offset_july: 9,
      type: "original",
    },
    {
      id: 260,
      name: "Asia/Ulaanbaatar",
      gmt_offset_january: 8,
      dst_offset_july: 9,
      type: "original",
    },
    {
      id: 261,
      name: "Asia/Urumqi",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 262,
      name: "Asia/Vientiane",
      gmt_offset_january: 7,
      dst_offset_july: 7,
      type: "original",
    },
    {
      id: 263,
      name: "Asia/Vladivostok",
      gmt_offset_january: 10,
      dst_offset_july: 11,
      type: "original",
    },
    {
      id: 264,
      name: "Asia/Yakutsk",
      gmt_offset_january: 9,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 265,
      name: "Asia/Yekaterinburg",
      gmt_offset_january: 5,
      dst_offset_july: 6,
      type: "original",
    },
    {
      id: 266,
      name: "Asia/Yerevan",
      gmt_offset_january: 4,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 267,
      name: "Atlantic/Azores",
      gmt_offset_january: -1,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 268,
      name: "Atlantic/Bermuda",
      gmt_offset_january: -4,
      dst_offset_july: -3,
      type: "original",
    },
    {
      id: 269,
      name: "Atlantic/Canary",
      gmt_offset_january: 0,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 270,
      name: "Atlantic/Cape_Verde",
      gmt_offset_january: -1,
      dst_offset_july: -1,
      type: "original",
    },
    {
      id: 271,
      name: "Atlantic/Faeroe",
      gmt_offset_january: 0,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 272,
      name: "Atlantic/Jan_Mayen",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 273,
      name: "Atlantic/Madeira",
      gmt_offset_january: 0,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 274,
      name: "Atlantic/Reykjavik",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 275,
      name: "Atlantic/South_Georgia",
      gmt_offset_january: -2,
      dst_offset_july: -2,
      type: "original",
    },
    {
      id: 276,
      name: "Atlantic/St_Helena",
      gmt_offset_january: 0,
      dst_offset_july: 0,
      type: "original",
    },
    {
      id: 277,
      name: "Atlantic/Stanley",
      gmt_offset_january: -3,
      dst_offset_july: -4,
      type: "original",
    },
    {
      id: 278,
      name: "Australia/Adelaide",
      gmt_offset_january: 10,
      dst_offset_july: 9,
      type: "original",
    },
    {
      id: 279,
      name: "Australia/Brisbane",
      gmt_offset_january: 10,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 280,
      name: "Australia/Broken_Hill",
      gmt_offset_january: 10,
      dst_offset_july: 9,
      type: "original",
    },
    {
      id: 281,
      name: "Australia/Currie",
      gmt_offset_january: 11,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 282,
      name: "Australia/Darwin",
      gmt_offset_january: 9,
      dst_offset_july: 9,
      type: "original",
    },
    {
      id: 283,
      name: "Australia/Hobart",
      gmt_offset_january: 11,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 284,
      name: "Australia/Lindeman",
      gmt_offset_january: 10,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 285,
      name: "Australia/Lord_Howe",
      gmt_offset_january: 11,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 286,
      name: "Australia/Melbourne",
      gmt_offset_january: 11,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 287,
      name: "Australia/Perth",
      gmt_offset_january: 8,
      dst_offset_july: 8,
      type: "original",
    },
    {
      id: 288,
      name: "Australia/Sydney",
      gmt_offset_january: 11,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 289,
      name: "Europe/Amsterdam",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 290,
      name: "Europe/Andorra",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 291,
      name: "Europe/Athens",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 292,
      name: "Europe/Belgrade",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 293,
      name: "Europe/Berlin",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 294,
      name: "Europe/Bratislava",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 295,
      name: "Europe/Brussels",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 296,
      name: "Europe/Bucharest",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 297,
      name: "Europe/Budapest",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 298,
      name: "Europe/Chisinau",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 299,
      name: "Europe/Copenhagen",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 300,
      name: "Europe/Dublin",
      gmt_offset_january: 0,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 301,
      name: "Europe/Gibraltar",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 302,
      name: "Europe/Helsinki",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 303,
      name: "Europe/Istanbul",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 304,
      name: "Europe/Kaliningrad",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 305,
      name: "Europe/Kiev",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 306,
      name: "Europe/Lisbon",
      gmt_offset_january: 0,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 307,
      name: "Europe/Ljubljana",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 308,
      name: "Europe/London",
      gmt_offset_january: 0,
      dst_offset_july: 1,
      type: "original",
    },
    {
      id: 309,
      name: "Europe/Luxembourg",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 310,
      name: "Europe/Madrid",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 311,
      name: "Europe/Malta",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 312,
      name: "Europe/Mariehamn",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 313,
      name: "Europe/Minsk",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 314,
      name: "Europe/Monaco",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 315,
      name: "Europe/Moscow",
      gmt_offset_january: 3,
      dst_offset_july: 4,
      type: "original",
    },
    {
      id: 316,
      name: "Europe/Oslo",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 317,
      name: "Europe/Paris",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 318,
      name: "Europe/Prague",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 319,
      name: "Europe/Riga",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 320,
      name: "Europe/Rome",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 321,
      name: "Europe/Samara",
      gmt_offset_january: 4,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 322,
      name: "Europe/San_Marino",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 323,
      name: "Europe/Sarajevo",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 324,
      name: "Europe/Simferopol",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 325,
      name: "Europe/Skopje",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 326,
      name: "Europe/Sofia",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 327,
      name: "Europe/Stockholm",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 328,
      name: "Europe/Tallinn",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 329,
      name: "Europe/Tirane",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 330,
      name: "Europe/Uzhgorod",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 331,
      name: "Europe/Vaduz",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 332,
      name: "Europe/Vatican",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 333,
      name: "Europe/Vienna",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 334,
      name: "Europe/Vilnius",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 335,
      name: "Europe/Warsaw",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 336,
      name: "Europe/Zagreb",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 337,
      name: "Europe/Zaporozhye",
      gmt_offset_january: 2,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 338,
      name: "Europe/Zurich",
      gmt_offset_january: 1,
      dst_offset_july: 2,
      type: "original",
    },
    {
      id: 339,
      name: "Indian/Antananarivo",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 340,
      name: "Indian/Chagos",
      gmt_offset_january: 6,
      dst_offset_july: 6,
      type: "original",
    },
    {
      id: 341,
      name: "Indian/Christmas",
      gmt_offset_january: 7,
      dst_offset_july: 7,
      type: "original",
    },
    {
      id: 342,
      name: "Indian/Cocos",
      gmt_offset_january: 6,
      dst_offset_july: 6,
      type: "original",
    },
    {
      id: 343,
      name: "Indian/Comoro",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 344,
      name: "Indian/Kerguelen",
      gmt_offset_january: 5,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 345,
      name: "Indian/Mahe",
      gmt_offset_january: 4,
      dst_offset_july: 4,
      type: "original",
    },
    {
      id: 346,
      name: "Indian/Maldives",
      gmt_offset_january: 5,
      dst_offset_july: 5,
      type: "original",
    },
    {
      id: 347,
      name: "Indian/Mauritius",
      gmt_offset_january: 4,
      dst_offset_july: 4,
      type: "original",
    },
    {
      id: 348,
      name: "Indian/Mayotte",
      gmt_offset_january: 3,
      dst_offset_july: 3,
      type: "original",
    },
    {
      id: 349,
      name: "Indian/Reunion",
      gmt_offset_january: 4,
      dst_offset_july: 4,
      type: "original",
    },
    {
      id: 350,
      name: "Pacific/Apia",
      gmt_offset_january: -11,
      dst_offset_july: -11,
      type: "original",
    },
    {
      id: 351,
      name: "Pacific/Auckland",
      gmt_offset_january: 13,
      dst_offset_july: 12,
      type: "original",
    },
    {
      id: 352,
      name: "Pacific/Chatham",
      gmt_offset_january: 13,
      dst_offset_july: 12,
      type: "original",
    },
    {
      id: 353,
      name: "Pacific/Easter",
      gmt_offset_january: -5,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 354,
      name: "Pacific/Efate",
      gmt_offset_january: 11,
      dst_offset_july: 11,
      type: "original",
    },
    {
      id: 355,
      name: "Pacific/Enderbury",
      gmt_offset_january: 13,
      dst_offset_july: 13,
      type: "original",
    },
    {
      id: 356,
      name: "Pacific/Fakaofo",
      gmt_offset_january: -10,
      dst_offset_july: -10,
      type: "original",
    },
    {
      id: 357,
      name: "Pacific/Fiji",
      gmt_offset_january: 12,
      dst_offset_july: 12,
      type: "original",
    },
    {
      id: 358,
      name: "Pacific/Funafuti",
      gmt_offset_january: 12,
      dst_offset_july: 12,
      type: "original",
    },
    {
      id: 359,
      name: "Pacific/Galapagos",
      gmt_offset_january: -6,
      dst_offset_july: -6,
      type: "original",
    },
    {
      id: 360,
      name: "Pacific/Gambier",
      gmt_offset_january: -9,
      dst_offset_july: -9,
      type: "original",
    },
    {
      id: 361,
      name: "Pacific/Guadalcanal",
      gmt_offset_january: 11,
      dst_offset_july: 11,
      type: "original",
    },
    {
      id: 362,
      name: "Pacific/Guam",
      gmt_offset_january: 10,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 363,
      name: "Pacific/Honolulu",
      gmt_offset_january: -10,
      dst_offset_july: -10,
      type: "original",
    },
    {
      id: 364,
      name: "Pacific/Johnston",
      gmt_offset_january: -10,
      dst_offset_july: -10,
      type: "original",
    },
    {
      id: 365,
      name: "Pacific/Kiritimati",
      gmt_offset_january: 14,
      dst_offset_july: 14,
      type: "original",
    },
    {
      id: 366,
      name: "Pacific/Kosrae",
      gmt_offset_january: 11,
      dst_offset_july: 11,
      type: "original",
    },
    {
      id: 367,
      name: "Pacific/Kwajalein",
      gmt_offset_january: 12,
      dst_offset_july: 12,
      type: "original",
    },
    {
      id: 368,
      name: "Pacific/Majuro",
      gmt_offset_january: 12,
      dst_offset_july: 12,
      type: "original",
    },
    {
      id: 369,
      name: "Pacific/Marquesas",
      gmt_offset_january: -9,
      dst_offset_july: -9,
      type: "original",
    },
    {
      id: 370,
      name: "Pacific/Midway",
      gmt_offset_january: -11,
      dst_offset_july: -11,
      type: "original",
    },
    {
      id: 371,
      name: "Pacific/Nauru",
      gmt_offset_january: 12,
      dst_offset_july: 12,
      type: "original",
    },
    {
      id: 372,
      name: "Pacific/Niue",
      gmt_offset_january: -11,
      dst_offset_july: -11,
      type: "original",
    },
    {
      id: 373,
      name: "Pacific/Norfolk",
      gmt_offset_january: 11,
      dst_offset_july: 11,
      type: "original",
    },
    {
      id: 374,
      name: "Pacific/Noumea",
      gmt_offset_january: 11,
      dst_offset_july: 11,
      type: "original",
    },
    {
      id: 375,
      name: "Pacific/Pago_Pago",
      gmt_offset_january: -11,
      dst_offset_july: -11,
      type: "original",
    },
    {
      id: 376,
      name: "Pacific/Palau",
      gmt_offset_january: 9,
      dst_offset_july: 9,
      type: "original",
    },
    {
      id: 377,
      name: "Pacific/Pitcairn",
      gmt_offset_january: -8,
      dst_offset_july: -8,
      type: "original",
    },
    {
      id: 378,
      name: "Pacific/Ponape",
      gmt_offset_january: 11,
      dst_offset_july: 11,
      type: "original",
    },
    {
      id: 379,
      name: "Pacific/Port_Moresby",
      gmt_offset_january: 10,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 380,
      name: "Pacific/Rarotonga",
      gmt_offset_january: -10,
      dst_offset_july: -10,
      type: "original",
    },
    {
      id: 381,
      name: "Pacific/Saipan",
      gmt_offset_january: 10,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 382,
      name: "Pacific/Tahiti",
      gmt_offset_january: -10,
      dst_offset_july: -10,
      type: "original",
    },
    {
      id: 383,
      name: "Pacific/Tarawa",
      gmt_offset_january: 12,
      dst_offset_july: 12,
      type: "original",
    },
    {
      id: 384,
      name: "Pacific/Tongatapu",
      gmt_offset_january: 13,
      dst_offset_july: 13,
      type: "original",
    },
    {
      id: 385,
      name: "Pacific/Truk",
      gmt_offset_january: 10,
      dst_offset_july: 10,
      type: "original",
    },
    {
      id: 386,
      name: "Pacific/Wake",
      gmt_offset_january: 12,
      dst_offset_july: 12,
      type: "original",
    },
    {
      id: 387,
      name: "Pacific/Wallis",
      gmt_offset_january: 12,
      dst_offset_july: 12,
      type: "original",
    },
  ],
}
